name: buckets
path: git::https://github.com/awslabs/seedfarmer-modules.git//modules/storage/buckets?ref=release/1.0.0&depth=1
targetAccount: primary
targetRegion: us-east-1
parameters:
  - name: encryption-type
    value: SSE
---
name: dummy
path: git::https://github.com/awslabs/seedfarmer-modules.git//modules/dummy/blank?ref=release/1.0.0&depth=1
targetAccount: primary
targetRegion: us-east-1
parameters:
  - name: testingRegionParams
    valueFrom:
      parameterValue: myTestRegionParam
  - name: testingGlobalParams
    valueFrom:
      parameterValue: myTestGlobalParam

