nameGenerator:
  prefix: local-
  suffix:
    valueFrom:
      envVariable: GLOBAL_CUSTOM_DEPLOYMENT_NAME_IDENTIFIER
toolchainRegion: us-west-2
groups:
  - name: networking
    path: manifests/local/networking-modules.yaml
  - name: storage
    path: manifests/local/storage-modules.yaml
  - name: integration
    path: manifests/local/integration-modules.yaml
  - name: replication
    path: manifests/local/replicator-modules.yaml
  - name: compute
    path: manifests/local/compute-modules.yaml
  - name: database
    path: manifests/local/database-modules.yaml
  - name: orchestration
    path: manifests/local/orchestration-modules.yaml
targetAccountMappings:
  - alias: primary
    parametersGlobal:
      dockerCredentialsSecret: aws-idf-docker-credentials
    accountId:
      valueFrom:
        envVariable: PRIMARY_ACCOUNT
    default: true
    regionMappings:
      - region: us-west-2
        default: true

