name: basic-networking
path: modules/network/basic-cdk/
targetAccount: primary
parameters:
  - name: internet-accessible
    value: true
  # - name: local-zones
  #   value: 
  #     - eu-central-1-ham-1a